### ISSUE TITLE
bripipetools issues overview

### ISSUE THREAD

**Issue by spribitzer** [BenaroyaResearch/bripipetools#122]
This is a collection of issues that should be addressed during the next rework of `bripipetools`:

- [ ] add ATACseq #120 and Cut and Run functions
- [ ] push MiXCR data by project not flowcell #119 
- [ ] 10x to research database #118 
- [ ] rhapsody to research database (maybe even a general/manual push to database script)
- [ ] partial downloads from base space
- [ ] improve handling of files in `globus_batch_submit` folder #113 
- [ ] avoiding double submissions #114 
- [ ] write documentation on how to run flowcells (epigenetic, RNAseq, 10x, rhapsody,...)
- [ ] in general: handle create/delete folders commands more gracefully
- [ ] cleanup /archive workflows, update annotations, and add new ones for ATAC/Cut and Run and update

**Comment by spribitzer** [comment]
- [ ] verify integrity of data _before_ wrapping up, e.g. make sure all the metrics are files, and not folder. ideally there would be a list of libraries that are missing something at the end
